### ISSUE TITLE
Content module to serve page content

### ISSUE THREAD

**Issue by KerimCETINBAS** [stellayazilim/stella.backend.tenant#6]
## content module to serve page content

store page contents in a static file, 
  - json
  - yaml
  - md
Astro and svelte-kit capable of parsing markdown files

```yaml
type: contact
content:
  - phone: ...
  - address: ...
  - ....
title: contact page
....

```
